In [ ]:
import sklearn.datasets as datasets

# Sklearn toy datasets

Inside package "sklearn.datasets" we can access a number of well-known datasets. We can use the methods "sklearn.datasets.load_<dataset_name>()". The loaded dataset is returned in the form of a dictionary with the following keys:
* 'data': dataset input features
* 'target': desired output
* 'DESCR': String description of the dataset.

Iris plants dataset (classification)

In [8]:
iris = datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Boston house prices dataset (regression)

In [7]:
boston = datasets.load_boston()
print(boston.DESCR)


.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

## Using our own data with scikit-learn estimators

The class "sklearn.feature_extraction.DictVectorizer" allow us to transform a dictionary of features into vector form.
* When feature values are strings, this transformer will do a binary one-hot (aka one-of-K) coding
* If a feature value is a sequence or set of strings, this transformer will iterate over the values and will count the occurrences of each string value.
* Note that this transformer will only do a binary one-hot encoding when feature values are of type string
 * For categorical features are represented as numeric values use OneHotEncoder after

Some important methods:
* fit(X[, y]) Learn a list of feature name -> indices mappings.
* transform(X) Transform feature->value dicts to array or sparse matrix.
* fit_transform(X[, y]) Learn a list of feature name -> indices mappings and transform X.
 * Like fit(X) followed by transform(X), but does not require materializing X in memory.
* get_feature_names() Returns a list of feature names, ordered by their indices.

In [17]:
from sklearn.feature_extraction import DictVectorizer

dataset = [
    {"feature1": "value1", "feature2": 1.0, "feature3": True},
    {"feature1": "value2", "feature2": 1.5, "feature3": False},
    {"feature1": "value3", "feature2": 2, "feature3": True},
]

dv = DictVectorizer()
ds = dv.fit_transform(dataset)
print("Dataset vectorized:", ds.toarray())
print("Features:", dv.get_feature_names())

Dataset vectorized: [[1.  0.  0.  1.  1. ]
 [0.  1.  0.  1.5 0. ]
 [0.  0.  1.  2.  1. ]]
Features: ['feature1=value1', 'feature1=value2', 'feature1=value3', 'feature2', 'feature3']


## Preprocessing

Package "sklearn.preprocessing"

### Standarization

"sklearn.preprocessing.StandardScaler"
* Standardize features by removing the mean and scaling to unit variance
* The standard score of a sample x is calculated as: z = (x - u) / s


Some methods:
* fit(X[, y, sample_weight]) Compute the mean and std to be used for later scaling.
* transform(X[, copy])  Perform standardization by centering and scaling
* fit_transform(X[, y]) Fit to data, then transform it.

In [22]:
from  sklearn.preprocessing import StandardScaler

ss = StandardScaler()
aux_data = [
    [1, 0, 2],
    [1.5, 12, 3.2],
    [0.1, 3, 4.2],
]

ss.fit(aux_data)
z_data = ss.transform(aux_data)
print(f'Means={ss.mean_},\nVariances={ss.var_}')
print(f'Standarized data:\n {z_data}')

Means=[0.86666667 5.         3.13333333],
Variances=[ 0.33555556 26.          0.80888889]
Standarized data:
 [[ 0.23017414 -0.98058068 -1.26012384]
 [ 1.09332714  1.37281295  0.07412493]
 [-1.32350128 -0.39223227  1.18599891]]


### Scaling features to a range

We can use:
* sklearn.preprocessing.MinMaxScaler([feature_range=(min, max)])
 * Transform features by scaling each feature to a given range.
* sklearn.preprocessing.MaxAbsScaler()
 * This estimator scales and translates each feature individually such that the maximal absolute value of each feature in the training set will be 1.0.
 * It does not shift/center the data, and thus does not destroy any sparsity.

For both use .fit() and .transform() or .fit_transform()

Check:
* https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#sphx-glr-auto-examples-preprocessing-plot-all-scaling-py

NOTES from URL:
* Both StandardScaler and MinMaxScaler are very sensitive to the presence of outliers.
* MaxAbsScaler also suffers from the presence of large outliers.

In [23]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler

sample_data = [
    [-1, 0 , 10],
    [2, -3, 4],
    [5, 6, 5]
]

mms = MinMaxScaler()
mas = MaxAbsScaler()

mms_out= mms.fit_transform(sample_data)
mas_out= mas.fit_transform(sample_data)
print(f'MinMaxScaled=\n{mms_out}\nMaxAbsScaled=\n{mas_out}')


MinMaxScaled=
[[0.         0.33333333 1.        ]
 [0.5        0.         0.        ]
 [1.         1.         0.16666667]]
MaxAbsScaled=
[[-0.2  0.   1. ]
 [ 0.4 -0.5  0.4]
 [ 1.   1.   0.5]]


## Other transformations

* sklearn.preprocessing.OneHotEncoder
* sklearn.preprocessing.KBinsDiscretizer: discretizes features into k bins
* sklearn.preprocessing.Binarizer(threshold=0.0): feature binarization is the process of thresholding numerical features to get boolean values
* sklearn.feature_extraction.text.CountVectorizer(ngram_rangetuple=(min_n, max_n), min_df=1,...): implements both tokenization and occurrence counting
 * vectorizer.fit_transform(corpus)
 * analyze = vectorizer.build_analyzer()
* sklearn.preprocessing.PolynomialFeatures: generates polynomial and interaction features up to a given degree. E.g. [a,b], degree=2 yields [1, a, b, a², ab, b²]
* sklearn.compose.ColumnTransformer(transformers...): Transformers is a list of tuples (name, transformer, columns)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    "Sample text",
    "Another sample",
    "sample content"
]

vectorizer = CountVectorizer()
vectorizer.fit_transform(corpus)
analyze = vectorizer.build_analyzer()
new_text = "Another sample text content"
print(vectorizer.vocabulary_)
print(analyze(new_text))
print(vectorizer.transform(analyze(new_text)).toarray())
print(vectorizer.transform([new_text]).toarray())


{'sample': 2, 'text': 3, 'another': 0, 'content': 1}
['another', 'sample', 'text', 'content']
[[1 1 1 1]]
[[1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]]


## Pipelines

Pipelines can be used to chain multiple estimators into one.
* sklearn.pipeline.Pipeline or sklearn.pipeline.make_pipeline (fills the names of the pipeline steps)
* Encapsulate data preprocessing and model
* Call fit(), fit_transform(), predict()... only once!
* All estimators in a pipeline, except the last one, must be transformers

You can access the pipeline paramers for all steps with:
* pipe.pipe.set_params(<estimator>__<parameter>=value)

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

from  sklearn.preprocessing import MinMaxScaler
from  sklearn.preprocessing import PolynomialFeatures

import numpy as np

pl1 = Pipeline([('step_1', MinMaxScaler())])
pl2 = make_pipeline(MinMaxScaler(), PolynomialFeatures(2))

#Changing default parameters
pl1.set_params(step_1__feature_range=(0,1))
pl2.set_params(minmaxscaler__feature_range=(0,1))

X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Pipeline1", pl1.fit_transform(X))
print("Pipeline2", pl2.fit_transform(X))

Pipeline1 [[0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5]
 [1.  1.  1.  1. ]]
Pipeline2 [[1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.  ]
 [1.   0.5  0.5  0.5  0.5  0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25
  0.25]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
  1.  ]]


# Supervised Learning

Class RegressorMixin has method:
* score(X, y, sample_weight=None) Returns the coefficient of determination $R^2$ of the prediction.

Class ClassifierMixin has method:
* score(X, y, sample_weight=None). Returns the mean accuracy on the given test data and labels.

## Linear Models

Base class LinearModel has methods
* fit(X, y)
* predict(X).
See: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model

### Regression: Linear regression
* sklearn.linear_model.LinearRegression
* $h_\theta(x) = \theta^T x$ ($x_0$=1)
* Minimization objective: $\min_{w} || X w - y||_2^2$

Some attributes:
* coef_: array of shape (n_features, ) or (n_targets, n_features). Estimated coefficients for the linear regression problem.
* intercept_: float or array of shape (n_targets,). Independent term in the linear model.

### Classification: Logistic regression
* sklearn.linear_model.LogisticRegression(penalty='l2')
* $h_\theta(x) = P(y=1 | x; \theta) = g(\theta^Tx) = \frac{1}{1+e^{-\theta^Tx}}$
 * $g(z)\ge 0.5\ when\ z \ge 0$
 * $x_0$=1
* Minimization objective
 * $\min_{w, c} regularizationTerm + \sum_{i=1}^n \log(\exp(- y_i (X_i^T w + c)) + 1)$

Some attributes:
* coef_ : coef_ndarray of shape (1, n_features) or (n_classes, n_features). Coefficient of the features in the decision function.
* intercept_: intercept_ndarray of shape (1,) or (n_classes,). Intercept (a.k.a. bias) added to the decision function.

## Support Vector Machines (SVM)

### SVM and kernels (a.k.a. "the kernel trick")
We can map from a non-linearly separable data into a higher dimension where the linear classifier is able separate them. The idea is:
* Choose some landmarks $l^{(i)}$ and a similarity function $f_i(x, l^{(i)})$called kernel.
* Use $f_i(x, l^{(i)})$ as features for our SVM. We have mapped from an n-dimensional space (number of original features of x) to a m-dimensional space (number of landmarks). Usually $m>>n$.

### sklearn SVM API

Classification with SVC: sklearn.svm.SVC
Regression with SVR: sklearn.svm.SVR

* Some common parameters (kernel='rbf', degree=3, C=1.0)
 * kernel={‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}
  * If kernel='poly' constructor parameter degree is used.
  * For linear kernel is faster to use sklearn.svm.LinearSVC or sklearn.svm.LinearSVR
 * C: Regularization parameter
* use fit(X,y) and predict(X) as usual

## Stochastic Gradient Descent (SGD)

Gradient Descent:
* If a multivariate function $F(x)$ is differentiable in the neighbourhood of a point $a$, then $F(x)$ decreases fastest in the direction of the negative gradient at $a$, that is $- \nabla F(a)$.
* Analogy: descending a foggy mountain, you only see a certain area close to you with the goal of reaching the lowest ground.
* Feature Scaling: make sure that all features have similar value ranges, it helps gradient descent to converge faster.
* We can search the minimum by following an iterative process such as:
 * $a_{n+1}=a_n - \alpha \nabla F(a_n) ; n \ge 0$.
 * $\alpha$ is the learning rate

Gradient Checking:
* Less efficient
* Instead of calculating the derivative to obtain the gradient at a given point you can numerically approximate the derivative by calculating:
 * $\frac{\delta f}{\delta \theta} \simeq \frac{f(\theta+\epsilon)-f(\theta-\epsilon)}{2\epsilon}$

SGD is sensitive to feature scaling!

sklearn's SGD API:
* Classification: sklearn.linear_model.SGDClassifier(loss='hinge', *, penalty='l2', alpha=0.0001, ...)
* Regression: sklearn.linear_model.SGDRegressor(loss='squared_loss', *, penalty='l2', alpha=0.0001, ...)

Model used internally depends on selected loss function L.

Some SGDClassifier Losses:
* ‘hinge’: SVC
* ‘log’: Logistic Regression
* ‘perceptron’: Perceptron

Example of loss for SGDRegressor:
* ‘epsilon_insensitive‘: SVR

In [6]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

sgdr = SGDRegressor(loss="epsilon_insensitive")
reg = make_pipeline(StandardScaler(),
                    sgdr)
boston = datasets.load_boston()
reg.fit(boston.data, boston.target)

0.7051448463579146

## Evaluation

* Train & test: sklearn.model_selection.train_test_split
 * Parameters: train_size, test_size, shuffle...
 * X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
* K-Fold evaluation: sklearn.model_selection import cross_val_score
 * scoring: str or callable, default=None (None uses estimator.score)
 * cv: if int number of folds
 * scores = cross_val_score(estimator, X, y, cv=5)
 * To just obtain sample indexes use class:
 sklearn.model_selection.KFold(n_splits=5, shuffle=False)

## Hyper-parameter tuning for an estimator

### Exahustive grid search: GridSearchCV

sklearn.model_selection.GridSearchCV(estimator, param_grid, cv=None)
* param_grid: dict or list of dictionaries. Dictionary with parameters names (str) as keys and lists of parameter
settings to try as values, or a list of such dictionaries, in which case the grids spanned by each dictionary in the
list are explored. This enables searching over any sequence of parameter settings.

Attributes:
* cv_results_: dict of numpy (masked) ndarrays. A dict with keys as column headers and values as columns,
that can be imported into a pandas
 * cv_results_['params']
 * cv_results_['mean_test_score']
 * cv_results_['std_test_score']
 * cv_results_['rank_test_score']


Example:

In [8]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.model_selection import GridSearchCV


param_grid = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 ]

iris = datasets.load_iris()
svc = SVC()
gs = GridSearchCV(svc, param_grid)
gs.fit(iris.data, iris.target)
print(gs.cv_results_)

r = gs.cv_results_
aux = zip(r['rank_test_score'], r['mean_test_score'], r['std_test_score'], r['params'])

print("*** Ranking ***")
print("'rank_test_score', 'mean_test_score', 'std_test_score', 'params'")
for s in sorted(aux, key=lambda x: x[0]):
    print(s)

{'mean_fit_time': array([0.00164809, 0.00241776, 0.00177445, 0.00089526, 0.00365567,
       0.00139771, 0.0012816 , 0.00138402, 0.00081639, 0.00153627,
       0.00086417, 0.00097666]), 'std_fit_time': array([4.56387757e-04, 1.70663237e-03, 1.34842172e-03, 1.19837157e-04,
       1.78645470e-03, 8.67468365e-05, 1.89308351e-04, 6.82445436e-05,
       1.04213020e-04, 6.19928700e-04, 2.02842548e-04, 2.41057271e-04]), 'mean_score_time': array([0.00074277, 0.00179725, 0.00054688, 0.00035481, 0.00218978,
       0.00139103, 0.00081587, 0.0010664 , 0.0005816 , 0.00136476,
       0.00052099, 0.00061221]), 'std_score_time': array([2.11902356e-04, 2.09223213e-03, 2.06635577e-04, 2.36370829e-05,
       1.21060461e-03, 9.22656165e-04, 3.00116550e-04, 4.83536917e-04,
       1.94581382e-04, 1.35006829e-03, 2.16110807e-04, 1.73528661e-04]), 'param_C': masked_array(data=[1, 10, 100, 1000, 1, 1, 10, 10, 100, 100, 1000, 1000],
             mask=[False, False, False, False, False, False, False, False,
     

### Randomized search: RandomizedSearchCV

Class sklearn.model_selection.RandomizedSearchCV(estimator, param_distributions, n_iter=10, cv=None)
* The parameters of the estimator used to apply these methods are optimized by cross-validated search over parameter settings.
* In contrast to GridSearchCV, not all parameter values are tried out, but rather a fixed number of parameter settings is sampled from the specified distributions.
* The number of parameter settings that are tried is given by n_iter

To use as sampling sources for parameters:
* scipy.stats: contains many useful distributions for sampling parameters, such as expon, gamma, uniform or randint

Attributes:
* cv_results_ Same as GridSearchCV

Rewritting the previous example:

In [10]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.model_selection import RandomizedSearchCV
from scipy import stats

param_grid = [
  {'C': stats.expon(scale=100), 'kernel': ['linear']},
  {'C': stats.expon(scale=100), 'gamma': stats.expon(scale=.1), 'kernel': ['rbf']},
 ]

iris = datasets.load_iris()
svc = SVC()
rs = RandomizedSearchCV(svc, param_grid)
rs.fit(iris.data, iris.target)
print(rs.cv_results_)

r = rs.cv_results_
aux = zip(r['rank_test_score'], r['mean_test_score'], r['std_test_score'], r['params'])

print("*** Ranking ***")
print("'rank_test_score', 'mean_test_score', 'std_test_score', 'params'")
for s in sorted(aux, key=lambda x: x[0]):
    print(s)

{'mean_fit_time': array([0.00229697, 0.00185022, 0.00310378, 0.00091558, 0.00074172,
       0.00072236, 0.00155997, 0.00166278, 0.0035604 , 0.00082569]), 'std_fit_time': array([4.91073830e-04, 2.80256901e-04, 1.56560530e-03, 9.19531223e-05,
       4.61151087e-05, 3.83023436e-05, 7.98422537e-04, 4.58152412e-04,
       2.19651904e-03, 1.76852493e-04]), 'mean_score_time': array([0.00190945, 0.00104795, 0.00100851, 0.00042443, 0.00039067,
       0.00042119, 0.00145483, 0.00078583, 0.001297  , 0.00035419]), 'std_score_time': array([1.04700597e-03, 4.49275014e-04, 4.32861416e-04, 1.02917477e-04,
       9.70285234e-05, 1.42976423e-05, 9.17269891e-04, 2.86094665e-04,
       1.09829356e-03, 2.71590472e-05]), 'param_C': masked_array(data=[116.57927393251535, 11.727100455923349,
                   45.40914254800396, 280.9361064133187, 93.9658882867794,
                   10.285405755198006, 122.93602244206532,
                   18.847857728957223, 169.11015045498675,
                   111.55614